// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chat-redesign/AppleChat.tsx": () => import("../components/mockups/chat-redesign/AppleChat.tsx"),
  "./components/mockups/chat-redesign/MotivDesktop.tsx": () => import("../components/mockups/chat-redesign/MotivDesktop.tsx")
};
